### ISSUE TITLE
Именование файлов

### ISSUE THREAD

**Issue by pavel-niukalo** [Shinimah/shop-pm#1]
Стоит придерживаться единообразия при именовании файлов.

Например, сейчас в папке `icons/` применяется несколько стилей именование, примеры:
- `Left.svg`
- `start-half.svg`
- `Right Icons.svg`

**Comment by khatskelevich** [comment]
Абсолютно неинформативное именование файлов. Строго требуется избегать такого именования. Название файлов должно емко описывать его содержание.  
Что такое CompOne и чем оно отличается от CompTwo?😡
![image](https://user-images.githubusercontent.com/17164182/204240487-a57ee0bc-ca7e-4b2a-9dac-19607de0a225.png)

**Comment by pavel-niukalo** [comment]
Можно опираться на наши соглашения

![image](https://user-images.githubusercontent.com/52506235/204241891-1a25932a-7874-4f66-b28f-0d5932bbf715.png)
