### ISSUE TITLE
Валидная верстка

### ISSUE THREAD

**Issue by pavel-niukalo** [Shinimah/shop-pm#6]
Верстка должна быть валидна (проходить [валидатор](https://validator.w3.org/))

1. Например, компонент [`CompTwo.vue`](https://github.com/Shinimah/shop-pm/blob/414c15376df7431fef4f1f451c64baf78059bd62/src/components/CompTwo.vue#L6) - `div` нельзя вкладывать в кнопки

![image](https://user-images.githubusercontent.com/52506235/204235111-631c2068-d598-4791-a965-5d684bef4248.png)

Чтобы быстро проверить, что во что можно вкладывать, рекомендую пользоваться ресурсом [`Can I Include`](https://caninclude.glitch.me/).

2. У тега `img` атрибут `alt` обязателен, даже пустой. Без этого атрибута валидатор выкинет ошибку

**Comment by khatskelevich** [comment]
3. В теге head есть небольшая ошибка вместо src в `<link src="./sprite.svg">` нужно использовать href
